#!/usr/bin/env bash
# Script that install and configure HAproxy on a server
sudo apt update -y
sudo apt-get -y install haproxy

haproxy_config="
frontend my_web
        bind *:80
        default_backend my_web_backend

backend my_web_backend
        server 18614-web-01 54.173.237.68:80 check
        server 18614-web-02 54.157.161.250:80 check"

sudo echo "$haproxy_config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
