#!/usr/bin/env bash
# Script that install and configure HAproxy on a server
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 18614-web-01 54.173.237.68:80 check\n\tserver 18614-web-02 54.157.161.250:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
